export { BankNameView } from './bankNameView'
export { BankAddressView } from './bankAddressView'
export { BankContactsView } from './bankContactsView'
export { BankSwiftView } from './bankSwiftView'
export { BankInformationVerifyView } from './bankInformationVerifyView'
export { SuccessView } from './successView'
export { ErrorView } from './errorView'
