import {
  CreateCurrencyRequestData,
  Currency,
  CurrencyStatus,
  CurrencyUsageInBank,
  GetCurrenciesResponseData,
} from '../types'

export const getCurrenciesResponseMock: GetCurrenciesResponseData = {
  page: 1,
  limit: 10,
  totalItems: 9,
  data: [
    {
      id: '1',
      name: 'CFA Franc BEAC',
      alphabeticCode: 'XAF',
      numericCode: 950,
      symbol: '$',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.NonCash],
      status: CurrencyStatus.Active,
    },
    {
      id: '2',
      name: 'Euro',
      alphabeticCode: 'EUR',
      numericCode: 978,
      symbol: '€',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.NonCash],
      status: CurrencyStatus.Active,
    },
    {
      id: '3',
      name: 'Japanese Yen',
      alphabeticCode: 'JPY',
      numericCode: 392,
      symbol: '¥',
      numberOfDecimals: 0,
      usageInBank: [
        CurrencyUsageInBank.LegalTender,
        CurrencyUsageInBank.NonCash,
        CurrencyUsageInBank.Reference,
      ],
      status: CurrencyStatus.Inactive,
    },
    {
      id: '4',
      name: 'US Dollar',
      alphabeticCode: 'USD',
      numericCode: 840,
      symbol: '$',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.Cash, CurrencyUsageInBank.NonCash],
      status: CurrencyStatus.Active,
    },
    {
      id: '5',
      name: 'British Pound Sterling',
      alphabeticCode: 'GBP',
      numericCode: 826,
      symbol: '£',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.Cash, CurrencyUsageInBank.NonCash],
      status: CurrencyStatus.Inactive,
    },
    {
      id: '6',
      name: 'Canadian Dollar',
      alphabeticCode: 'CAD',
      numericCode: 124,
      symbol: '$',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.LegalTender, CurrencyUsageInBank.NonCash],
      status: CurrencyStatus.Active,
    },
    {
      id: '7',
      name: 'Australian Dollar',
      alphabeticCode: 'AUD',
      numericCode: 136,
      symbol: '$',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.Reference, CurrencyUsageInBank.Cash],
      status: CurrencyStatus.Active,
    },
    {
      id: '8',
      name: 'Swiss Franc',
      alphabeticCode: 'CHF',
      numericCode: 756,
      symbol: 'CHF',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.NonCash, CurrencyUsageInBank.LegalTender],
      status: CurrencyStatus.Inactive,
    },
    {
      id: '9',
      name: 'Chinese Yuan',
      alphabeticCode: 'CNY',
      numericCode: 156,
      symbol: '¥',
      numberOfDecimals: 2,
      usageInBank: [CurrencyUsageInBank.LegalTender, CurrencyUsageInBank.Cash],
      status: CurrencyStatus.Active,
    },
  ],
}

export const createCurrencyRequestDataMock: CreateCurrencyRequestData = {
  id: '9',
  name: 'Chinese Yuan',
  alphabeticCode: 'CNY',
  numericCode: 156,
  symbol: '¥',
  numberOfDecimals: 2,
  usageInBank: [CurrencyUsageInBank.LegalTender, CurrencyUsageInBank.Cash],
  status: CurrencyStatus.Active,
}

export const getAllCurrenciesResponseMock: Currency[] = [
  {
    id: '1',
    name: 'CFA Franc BEAC',
    alphabeticCode: 'XAF',
    numericCode: 950,
    symbol: '$',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.Cash, CurrencyUsageInBank.NonCash],
    status: CurrencyStatus.Active,
  },
  {
    id: '2',
    name: 'Euro',
    alphabeticCode: 'EUR',
    numericCode: 978,
    symbol: '€',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.NonCash],
    status: CurrencyStatus.Active,
  },
  {
    id: '3',
    name: 'Japanese Yen',
    alphabeticCode: 'JPY',
    numericCode: 392,
    symbol: '¥',
    numberOfDecimals: 0,
    usageInBank: [
      CurrencyUsageInBank.LegalTender,
      CurrencyUsageInBank.NonCash,
      CurrencyUsageInBank.Reference,
    ],
    status: CurrencyStatus.Inactive,
  },
  {
    id: '4',
    name: 'US Dollar',
    alphabeticCode: 'USD',
    numericCode: 840,
    symbol: '$',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.Cash, CurrencyUsageInBank.NonCash],
    status: CurrencyStatus.Active,
  },
  {
    id: '5',
    name: 'British Pound Sterling',
    alphabeticCode: 'GBP',
    numericCode: 826,
    symbol: '£',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.Cash, CurrencyUsageInBank.NonCash],
    status: CurrencyStatus.Inactive,
  },
  {
    id: '6',
    name: 'Canadian Dollar',
    alphabeticCode: 'CAD',
    numericCode: 124,
    symbol: '$',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.LegalTender, CurrencyUsageInBank.NonCash],
    status: CurrencyStatus.Active,
  },
  {
    id: '7',
    name: 'Australian Dollar',
    alphabeticCode: 'AUD',
    numericCode: 136,
    symbol: '$',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.Reference, CurrencyUsageInBank.Cash],
    status: CurrencyStatus.Active,
  },
  {
    id: '8',
    name: 'Swiss Franc',
    alphabeticCode: 'CHF',
    numericCode: 756,
    symbol: 'CHF',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.NonCash, CurrencyUsageInBank.LegalTender],
    status: CurrencyStatus.Inactive,
  },
  {
    id: '9',
    name: 'Chinese Yuan',
    alphabeticCode: 'CNY',
    numericCode: 156,
    symbol: '¥',
    numberOfDecimals: 2,
    usageInBank: [CurrencyUsageInBank.LegalTender, CurrencyUsageInBank.Cash],
    status: CurrencyStatus.Active,
  },
]
